### ISSUE TITLE
xiaomi_lywsd03 mmc: No values received

### ISSUE THREAD

**Issue by rubenkr** [atc1441/ATC_MiThermometer#217]
Dear all,

i have an issue I am unable to fix now since hours. After I upgraded the firmware on my ble device I am unable to receive the values on my ESP32. Before it was working great with ESPHOME on my ESP32.

- Flashed latest atc firmware
- Enabled Mi Like advertisement
- ESPHOME on ESP32 with dummy bindkey

The shell  on the ESP32 shows Found device: xxx Address: xxx Name: xxx . But it will not read actual values.

The config.yaml looks like on the manual:
```
sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:B1:CD:7F"
    bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "LYWSD03MMC Temperature"
    humidity:
      name: "LYWSD03MMC Humidity"
    battery_level:
      name: "LYWSD03MMC Battery Level"
```

Any help is much appreciated !
