### ISSUE TITLE
No data in HomeAssistant

### ISSUE THREAD

**Issue by joshuagti** [atc1441/ATC_MiThermometer#98]
Trying here to see if anyone has any insight! Using an ESP32.

Firstly I used the tool to get the bindkey to enter into Esphome and although it would see the device and using the generated bindkey it would not show any sensor data.

I then though to flash the firmware and it appears to have gone okay and flashes my MAC address on boot and the device name showing in the esp32 logs but still no sensor data (shows "unknown").

```
esp32_ble_tracker:
sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:B7:F4:D7"
    bindkey: "ab1a981ed5b3ac61e0aac620b8c1939a"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Temp Sensor Battery Level"
```

Before I flashed I could see the temp data in the tool but now it shows "waiting for data, this will not change on devices with custom firmware" - unsure whether this is supposed to be like this? No device known ID, Mi token or Mi bindkey is also showing now.
